version: "3"

services:
  # mongo:
  #   image: mongo:5.0.17
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - "./mongodb/volumes:/data/db"
  server:
    image: node:19.0.0-alpine
    ports:
      - '3001:3000'
    user: node
    working_dir: /home/node
    volumes:
      - ./nest-app:/home/node
    command: npm run start:dev