import Head from 'next/head'
import HomeLayout from '@/components/layouts/Home'
import {useEffect} from "react";
import Card from '@/components/events/Card'

export default function Events() {
    useEffect(() =>
    {
        document.body.classList.add("bg-custom-light-orange");
    });

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <HomeLayout>
                <section>
                    <div className="container mx-auto mt-14 gap-5 flex items-center md:flex-row flex-col md:justify-start justify-center">
                    <img className="sm:w-20" src="./target.png"alt="..."/>
                    <h3 className="ml-4 font-medium md:text-4xl">Prochains événement</h3>
                </div>
                <Card/>
                </section>
                
            </HomeLayout>
        </>
)
}
