apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest
  template:
    metadata:
      labels:
        app: nest
    spec:
      containers:
        - name: nest
          image: rexrider/ludotter:$IMAGE_TAG
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: nest-service
spec:
  type: NodePort
  selector:
    app: nest
  ports:
    - name: nest
      port: 6000
      targetPort: 3000
      nodePort: 32000