name: Deploy MongoDB

on:
  push:
    branches:
      - master
    paths:
      - "docker-compose.yml"
      - ".github/workflows/docker.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - name: Build and push MongoDB Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./mongodb
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ludotter:mongodb
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}
