name: Deploy MongoDB

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/mongo.yml"
      - "kubernetes/mongo-deploy.yml"
      - "mongodb/Dockerfile"

jobs:
  Build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - name: Build and push MongoDB Docker image
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        uses: docker/build-push-action@v4
        with:
          context: ./mongodb
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ludotter:mongo-${{ steps.vars.outputs.sha_short }}

  Deploy:
    needs: Build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update image tag in Kubernetes deployment config
        uses: Charlyzzz/update-k8s-image@v1.7.1
        with:
          manifest-path: ./kubernetes/mongo-deploy.yml
          new-image-tag: mongo-${{ needs.Build-and-push.outputs.sha_short }}
          container-name: mongodb

      - name: Upload Kubernetes deployment config
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./kubernetes/mongo-deploy.yml
          target: /root

      - name: Deploy MongoDB
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            kubectl apply -f /root/kubernetes/mongo-deploy.yml