name: Deploy MongoDB

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/mongo.yml"
      - "./mongodb/Dockerfile"

jobs:
  Build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - name: Build and push MongoDB Docker image
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        uses: docker/build-push-action@v4
        with:
          context: ./mongodb
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ludotter:mongo-${{ steps.vars.outputs.sha_short }}

  Deploy:
    needs: Build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Upload Kubernetes deployment config
#        uses: appleboy/scp-action@v0.1.4
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          port: ${{ secrets.SSH_PORT }}
#          username: ${{ secrets.SSH_USERNAME }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          source: ./kubernetes/mongo.yml
#          target: /root
      - name: Upload Kubernetes deployment config
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SSH_HOST
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASSWORD }}
          scp: |
            ./kubernetes/mongo.yml => /root/
          last_ssh: |
            ls -la

#      - name: Start MongoDB deployment
#        uses: appleboy/ssh-action@v0.1.10
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          port: ${{ secrets.SSH_PORT }}
#          username: ${{ secrets.SSH_USERNAME }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          script: |
#            kubectl apply -f /root/mongo.yml