name: Deploy MongoDB

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/mongo.yml"
      - "./mongodb/Dockerfile"

jobs:
  Build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - name: Build and push MongoDB Docker image
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        uses: docker/build-push-action@v4
        with:
          context: ./mongodb
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ludotter:mongo-${{ steps.vars.outputs.sha_short }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

  Deploy:
    needs: Build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Kubernetes deployment config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_PASSWORD }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./kubernetes/mongo.yaml
          target: /root/mongo.yaml

      - name: Start MongoDB deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_PASSWORD }}
          password: ${{ secrets.SSH_PASSWORD }}
          env:
            IMAGE_TAG: ${{ needs.Build-and-push.outputs.sha_short }}
          script: |
            kubectl apply -f /root/mongo.yaml