name: Deploy Nest

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/nest.yml"
      - "./nest-app/**"

jobs:
  Build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}
      - name: Set sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build and push Nest Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./nest-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ludotter:nest-${{ steps.vars.outputs.sha_short }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}
